### ISSUE TITLE
关于"Transformer-based Reasoning for Learning Evolutionary Chain  of Events on Temporal Knowledge Graph " 论文的一些疑问

### ISSUE THREAD

**Issue by cai-yuxiang** [seeyourmind/TKGElib#2]
I recently saw your work published on SIGIR 2024 and was very interested. I am a little confused about the results in Table 2. Do the results of eceformer means that predict the T + 1 moment (s, R, ?) based on historical TKG? I mainly see that one of your baseline Stoke comparisons is actually in the interpolation setting, and the L2TKG above is in the extrapolation setting? So I have these doubts.

I hope you can help me answer my questions at your convenience. I would appreciate it!

**Comment by H-chenglei** [comment]
I would like to know how the ECE chronological construction is implemented in code.
I would be grateful if you could take the time to help me with my questions.

**Comment by seeyourmind** [comment]
@H-chenglei Perhaps you can find the answer at [this link](https://github.com/seeyourmind/TKGElib/blob/8defddeba2abd4924ec6785541952f550e75d878/kge/indexing.py#L344).
