### ISSUE TITLE
关于ICEWS14,ICEWS18,ICEWS05-15数据集的参数的最优参数

### ISSUE THREAD

**Issue by AugustUp** [seeyourmind/TKGElib#3]
请您公布一下关于ICEWS14,ICEWS18,ICEWS05-15数据集的最优参数，不胜感激

**Comment by seeyourmind** [comment]
@AugustUp 您好，不好意思我这边因为在这个模型的基础上做了新的工作使得原配置文件被修改了。不过，我们的这个模型本身是没有做过太多参数调整的，你可以使用GDELT的配置跑ICEWS的数据集，性能应该差不多。

**Comment by AugustUp** [comment]
感谢您的回复，祝您生活愉快 @seeyourmind

**Comment by thePOET8** [comment]
你好，按照最优参数跑的结果大概在什么区间，我也按GDELT的配置跑ICEWS的数据集，性能差别很大

**Comment by qry123x-cell** [comment]
> [@AugustUp](https://github.com/AugustUp) 您好，不好意思我这边因为在这个模型的基础上做了新的工作使得原配置文件被修改了。不过，我们的这个模型本身是没有做过太多参数调整的，你可以使用GDELT的配置跑ICEWS的数据集，性能应该差不多。

Why do so many people say that the results cannot be reproduced? May I ask if this metric is reliable?
